{% set data = load_setup_py_data() %}

package:
  name: photodiag
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  entry_points:
    - photodiag = photodiag.cli:main

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - bokeh =2.3
    - scipy >=0.17
    - pandas
    - h5py
    - numpy >=1.15

about:
  home: https://github.com/paulscherrerinstitute/photodiag
  summary: {{ data['description'] }}
  license: GNU GPLv3
  license_file: LICENSE
