{% set data = load_setup_py_data() %}

package:
  name: photodiag
  version: {{ data['version'] }}

source:
  path: ..

build:
  entry_points:
    - photodiag = photodiag.photodiag:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python>=3.5
    - bokeh==1.0.1
    - scipy>=1.1.0
    - pandas>=0.23.1
    - h5py>=2.8.0
    - bsread>=1.4.0
    - numpy>=1.15.0

about:
  home: https://git.psi.ch/usov_i/photodiag
  summary: {{ data['description'] }}
  license: GNU GPLv3
  license_file: LICENSE
